spring:
  cloud:
    discovery:
      enabled: false #Disable discovery
    config:
      enabled: false
    services:
      registrationMethod: direct
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://demo.uaa.sys.moraga.cf-app.com/oauth/token"
  jpa:
    hibernate:
      ddl-auto: update
