spring:
  cloud:
    discovery:
      enabled: false #Disable discovery
    config:
      enabled: false
    services:
      registrationMethod: direct
    loadbalancer:
      ribbon:
        enabled: false # enables Spring Cloud Loadbalancer
  jpa:
    hibernate:
      ddl-auto: update


