spring:
  cloud:
    discovery:
      enabled: false #Disable discovery
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://demo.uaa.sys.moraga.cf-app.com/oauth/token"
demo:
  service-a: "https://service-a.apps.moraga.cf-app.com"
  service-b: "service-b"

